stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw
    outs:
      - data/prepared

  train:
    cmd: python src/train.py
    deps:
      - data/prepared
      - src/train.py
    outs:
      - models/model.pkl
    metrics:
      - metrics/accuracy.json

